### ISSUE TITLE
AUTO_MOUSE_THRESHOLD が設定できるとうれしいです

### ISSUE THREAD

**Issue by tokuhirom** [sekigon-gonnoc/torabo-tsuki#2]
torabo-tsuki を購入させていただきまして、便利に使わせていただいております。

AML を使っているときに、うっかりちょっとだけボールにふれてしまって AML が有効になってしまうケースが結構あります。
[via-custom-ui-for-vial](https://sekigon-gonnoc.github.io/via-custom-ui-for-vial/) で AUTO_MOUSE_THRESHOLD が調整できると快適になるかなぁと思うのですがいかがでしょうか。

**Comment by sekigon-gonnoc** [comment]
v1.2.1で追加しました
https://sekigon-gonnoc.github.io/BLE-Micro-Pro-WebConfigurator/#/update/application

**Comment by tokuhirom** [comment]
ありがとうございます！！
